// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Create & Update & Delete Doctors', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Create & Update & Delete Doctors', async function() {
    await driver.get("http://localhost:1604/")
    await driver.manage().window().setRect({ width: 1440, height: 804 })
    await driver.findElement(By.linkText("Sign In")).click()
    await driver.findElement(By.id("username")).click()
    await driver.findElement(By.id("username")).sendKeys("minhle")
    await driver.findElement(By.id("password")).sendKeys("leminh")
    await driver.findElement(By.css(".btn")).click()
    await driver.findElement(By.name("firstName")).click()
    await driver.findElement(By.name("firstName")).sendKeys("Test")
    await driver.findElement(By.xpath("//div[@id=\'root\']/section/div/div/aside/form/footer/div/div[2]/button/span")).click()
    await driver.findElement(By.name("lastName")).sendKeys("Create")
    await driver.findElement(By.css(".css-sedbkg-ButtonBase > .css-7no60z-ButtonBase")).click()
    await driver.findElement(By.xpath("//span[contains(.,\'A doctor has been added\')]")).click()
    await driver.findElement(By.css(".css-v3yuj6:nth-child(1) .css-1c9r9d4-ButtonBase > .css-7no60z-ButtonBase")).click()
    await driver.findElement(By.xpath("//div/form/div[2]/div/input")).sendKeys("Update")
    await driver.findElement(By.xpath("//div/form/div[3]/div/input")).sendKeys("Test")
    await driver.findElement(By.xpath("//div/form/footer/div/div[2]/button/span")).click()
    await driver.findElement(By.xpath("//span[contains(.,\'A doctor has been updated information\')]")).click()
    await driver.findElement(By.xpath("//span[contains(.,\'Delete\')]")).click()
    await driver.findElement(By.xpath("//span[contains(.,\'A doctor has been deleted\')]")).click()
  })
})
