// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Login & Logout Admin', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Login & Logout Admin', async function() {
    await driver.get("http://localhost:1604/")
    await driver.manage().window().setRect({ width: 1440, height: 804 })
    await driver.findElement(By.linkText("Sign In")).click()
    await driver.findElement(By.id("username")).click()
    await driver.findElement(By.id("username")).sendKeys("minhle")
    await driver.findElement(By.id("password")).sendKeys("leminh")
    await driver.findElement(By.css(".btn")).click()
    await driver.findElement(By.linkText("Sign Out")).click()
  })
})
